# Generated by scripts/gen_experiments.py — do not edit by hand.
export DESIGN_NICKNAME = ibex
export DESIGN_NAME     = ibex_core
export PLATFORM        = sky130hd
export VERILOG_FILES   = $(sort $(wildcard ./designs/src/ibex/*.v))
export SDC_FILE        = /home/user/Synthesis/config/ibex/sdc/clk15.sdc
export ADDER_MAP_FILE :=
export CORE_UTILIZATION  = 20
export CORE_ASPECT_RATIO = 1
export CORE_MARGIN       = 2
export FASTROUTE_TCL = $(PLATFORM_DIR)/fastroute_base.tcl
export PWR_NETS_VOLTAGES = "VDD 1.8"
export GND_NETS_VOLTAGES = "VSS 0.0"
