#!/usr/bin/env python3
"""E1 critical-path migration: worst setup path per clock-ladder point.

Shows whether the endpoint that limits Fmax moves as the constraint tightens.
Reuses parse_paths' block/path logic on each variant's signoff_sta.rpt.
"""
import argparse, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import parse_paths as pp


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--orfs-flow", required=True)
    ap.add_argument("--platform", default="sky130hd")
    ap.add_argument("--design", default="ibex")
    ap.add_argument("--variant", action="append", default=[], help="FLOW_VARIANT:label")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    rows = ["# E1 — critical-path migration", "",
            "_Auto-generated by `scripts/parse/crit_migration.py` (post-CTS STA). "
            "Worst setup path at each clock point._", "",
            "| Clock (ns) | Worst setup endpoint | Startpoint | Slack (ns) | Logic levels |",
            "|--:|---|---|--:|--:|"]
    for spec in a.variant:
        fv, _, label = spec.partition(":")
        rpt = os.path.join(a.orfs_flow, "reports", a.platform, a.design, fv, "signoff_sta.rpt")
        if not os.path.exists(rpt):
            rows.append(f"| {label or fv} | n/a | n/a | n/a | n/a |")
            continue
        t = open(rpt, errors="ignore").read()
        paths = sorted(pp.parse_paths(pp.split_block(t, "SETUP (max)", "HOLD (min)")),
                       key=lambda p: p["slack"])
        # worst real (core_clock) path, not the async reset removal check
        core = [p for p in paths if "async" not in p["grp"].lower()] or paths
        w = core[0] if core else None
        if w:
            rows.append(f"| {label or fv} | `{w['ep']}` | `{w['sp']}` | "
                        f"{w['slack']:+.3f} | {w['stages']} |")
        else:
            rows.append(f"| {label or fv} | n/a | n/a | n/a | n/a |")

    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    open(a.out, "w").write("\n".join(rows) + "\n")
    print(f"wrote {a.out}")
    print("\n".join(rows[5:]))


if __name__ == "__main__":
    main()
