#!/usr/bin/env python3
"""Single-run QoR -> markdown table. Numbers come from qor_lib (raw logs)."""
import argparse, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import qor_lib as q


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--design", required=True)
    ap.add_argument("--platform", required=True)
    ap.add_argument("--variant", default="base")
    ap.add_argument("--log-dir", required=True)
    ap.add_argument("--results-dir", required=True)
    ap.add_argument("--reports-dir", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    m = q.extract(a.log_dir, a.results_dir, a.reports_dir)
    rows = [
        ("Clock period (ns)",      q.fmt(m["period"], "{:.4f}")),
        ("Setup worst slack (ns)", q.fmt(m["setup_ws"], "{:+.4f}")),
        ("Hold worst slack (ns)",  q.fmt(m["hold_ws"], "{:+.4f}")),
        ("Setup TNS (ns)",         q.fmt(m["tns"], "{:+.4f}")),
        ("Setup violations",       q.fmt(m["setup_viol"])),
        ("Hold violations",        q.fmt(m["hold_viol"])),
        ("Achievable period (ns)", q.fmt(m["achievable"], "{:.4f}")),
        ("Implied Fmax (MHz)",     q.fmt(m["fmax"], "{:.1f}")),
        ("Design area (um^2)",     q.fmt(m["area"], "{:.0f}")),
        ("Core utilization (%)",   q.fmt(m["util"], "{:.1f}")),
        ("Total power (W)",        q.fmt(m["power"], "{:.3e}")),
        ("Clock buffers (CTS)",    q.fmt(m.get("clk_buffers"))),
        ("Route wirelength (um)",  q.fmt(m["wirelength"])),
        ("Vias",                   q.fmt(m["vias"])),
        ("Route DRC violations",   q.fmt(m["drc"])),
        ("Synth cell count",       q.fmt(m["cells"])),
    ]
    lines = [
        f"# QoR — {a.platform} / {a.design} / {a.variant}",
        "",
        "_Auto-generated by `scripts/parse/parse_flow.py` from ORFS logs. Do not edit._",
        "",
        "| Metric | Value |",
        "|---|---|",
        *[f"| {k} | {v} |" for k, v in rows],
        "",
    ]
    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    open(a.out, "w").write("\n".join(lines))
    print(f"wrote {a.out}")
    for k, v in rows:
        print(f"  {k:24s} {v}")


if __name__ == "__main__":
    sys.exit(main())
