#!/usr/bin/env python3
"""Extract top-5 setup + top-5 hold paths from a signoff_sta.rpt into a table
with the logic(cell) vs wire(net) delay split.

Delay split heuristic (sky130hd): in OpenSTA's full_clock_expanded path, each
pin row carries an incremental Delay. On a cell *output* pin it's the cell arc
delay; on a cell *input* pin it's the interconnect (wire) delay from the driving
net. sky130hd outputs are X/Y/Q/Q_N/CO/SUM/COUT/GCLK; everything else is an input.
"""
import argparse, os, re

OUT_PINS = {"X", "Y", "Q", "Q_N", "CO", "COUT", "SUM", "GCLK", "HI", "LO"}
ROW = re.compile(r"^\s*[\d.]+\s+([\d.]+)\s+[\d.]+\s+[v^]\s+(\S+)\s+\(sky130_fd_sc_hd__\w+\)",
                 re.M)


def split_block(text, start, end):
    s, e = text.find(start), text.find(end)
    return text[s:e if e > 0 else len(text)] if s >= 0 else ""


def parse_paths(section):
    """Yield dicts for each Startpoint..slack path block in a section."""
    blocks = re.split(r"(?=Startpoint:)", section)
    for b in blocks:
        sp = re.search(r"Startpoint:\s+(\S+)", b)
        ep = re.search(r"Endpoint:\s+(\S+)", b)
        gp = re.search(r"Path Group:\s+(\S+)", b)
        sl = re.findall(r"(-?\d+\.\d+)\s+slack \((?:MET|VIOLATED)\)", b)
        if not (sp and ep and sl):
            continue
        cell = wire = 0.0
        stages = 0
        for m in ROW.finditer(b):
            delay, pinfull = float(m.group(1)), m.group(2)
            inst, _, pin = pinfull.rpartition("/")
            if inst.startswith(("clkbuf", "clkinv", "clknet")):
                continue          # clock-tree insertion, not data-path delay
            if pin in OUT_PINS:
                cell += delay
                stages += 1
            else:
                wire += delay
        yield dict(sp=sp.group(1), ep=ep.group(1), grp=gp.group(1) if gp else "?",
                   slack=float(sl[-1]), cell=cell, wire=wire, stages=stages)


def table(paths, kind):
    tot = lambda p: p["cell"] + p["wire"]
    rows = ["", f"### Top-5 {kind} paths", "",
            "| # | Startpoint | Endpoint | Group | Slack (ns) | Logic ns | Wire ns | Wire % | Stages |",
            "|--:|---|---|---|--:|--:|--:|--:|--:|"]
    for i, p in enumerate(paths[:5], 1):
        wpct = 100 * p["wire"] / tot(p) if tot(p) else 0
        rows.append(f"| {i} | `{p['sp']}` | `{p['ep']}` | {p['grp']} | "
                    f"{p['slack']:+.3f} | {p['cell']:.2f} | {p['wire']:.2f} | "
                    f"{wpct:.0f}% | {p['stages']} |")
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rpt", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    t = open(a.rpt, errors="ignore").read()
    setup = sorted(parse_paths(split_block(t, "SETUP (max)", "HOLD (min)")),
                   key=lambda p: p["slack"])
    hold = sorted(parse_paths(split_block(t, "HOLD (min)", "CLOCK SKEW")),
                  key=lambda p: p["slack"])
    lines = ["# STA deep-dive — top setup/hold paths",
             "",
             "_Auto-generated by `scripts/parse/parse_paths.py` from the signoff "
             "STA report (extracted SPEF). Do not edit._",
             *table(setup, "setup (max)"),
             *table(hold, "hold (min)"), ""]
    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    open(a.out, "w").write("\n".join(lines))
    print(f"wrote {a.out}")
    print("setup worst:", setup[0] if setup else None)
    print("hold worst:", hold[0] if hold else None)


if __name__ == "__main__":
    main()
