#!/usr/bin/env python3
"""Pre-CTS vs post-CTS analysis for the Ibex baseline, straight from ORFS logs.

Extracts, for the clock tree TritonCTS built:
  - topology per clock net (sinks, buffers, leaf buffers, path depth, levels)
  - hold worst slack BEFORE vs AFTER CTS hold-repair (the violations CTS creates
    by giving the clock real insertion delay + skew, and that repair_timing -hold
    then fixes)
  - propagated skew + insertion delay (from the signoff STA report)
Emits a markdown report + a mermaid sketch of one domain's tree.
"""
import argparse, os, re, sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "parse"))
import qor_lib as q


def worst_slack_in_block(text, start_pat, end_pat):
    """Min 'N slack (MET|VIOLATED)' between start_pat and the next end_pat."""
    s = re.search(start_pat, text)
    if not s:
        return None
    rest = text[s.end():]
    e = re.search(end_pat, rest)
    block = rest[:e.start()] if e else rest
    vals = [float(x) for x in re.findall(r"(-?\d+\.\d+)\s+slack \((?:MET|VIOLATED)\)", block)]
    return min(vals) if vals else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--log-dir", required=True)
    ap.add_argument("--results-dir", required=True)
    ap.add_argument("--reports-dir", required=True)
    ap.add_argument("--clock-net", default="clk_i")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    cts = open(os.path.join(a.log_dir, "4_1_cts.log"), errors="ignore").read()

    # --- topology, per clock net (logged in order: clk_i then clk) ---
    nets    = re.findall(r'Clock net "([^"]+)" has (\d+) sinks', cts)
    created = re.findall(r"Created (\d+) clock buffers", cts)
    leaf    = re.findall(r"Leaf buffers (\d+)", cts)
    minbuf  = re.findall(r"Minimum number of buffers in the clock path: (\d+)", cts)
    maxbuf  = re.findall(r"Maximum number of buffers in the clock path: (\d+)", cts)
    levels  = re.findall(r"Max level of the clock tree: (\d+)", cts)

    topo = []
    for i, (net, sinks) in enumerate(nets):
        g = lambda L: L[i] if i < len(L) else "n/a"
        topo.append(dict(net=net, sinks=sinks, buffers=g(created), leaf=g(leaf),
                         minp=g(minbuf), maxp=g(maxbuf), level=g(levels)))

    # --- hold worst slack: pre-repair vs post-repair (path_delay min blocks) ---
    pre_hold  = worst_slack_in_block(cts, r"cts pre-repair report_checks -path_delay min",
                                     r"report_checks -path_delay max")
    post_hold = worst_slack_in_block(cts, r"cts post-repair report_checks -path_delay min",
                                     r"report_checks -path_delay max")

    # --- propagated skew + insertion from signoff STA report ---
    sta = os.path.join(a.reports_dir, "signoff_sta.rpt")
    skew = lat = None
    if os.path.exists(sta):
        t = open(sta, errors="ignore").read()
        seg = t[t.find("CLOCK SKEW"): t.find("WNS / TNS")] if "CLOCK SKEW" in t else ""
        nums = re.findall(r"(\d+\.\d+)\s+(\d+\.\d+)\s+(\d+\.\d+)", seg)  # latency crpr skew
        if nums:
            skew = float(nums[-1][2])
        lats = [float(x) for x in re.findall(r"^\s+(\d+\.\d+)\s*$", seg, re.M)]
        lat = max(lats) if lats else None

    clk_bufs_total = q.fnum(sum(int(c) for c in created)) if created else None

    # --- markdown ---
    L = ["# CTS analysis — Ibex baseline (sky130hd)", "",
         "_Auto-generated by `scripts/cts/cts_report.py` from ORFS CTS logs + signoff STA._", "",
         "## Pre-CTS vs post-CTS", "",
         "| Quantity | Pre-CTS (ideal clock) | Post-CTS (propagated) |",
         "|---|---|---|",
         "| Clock model | ideal (0 latency, 0 skew) | real buffer tree |",
         f"| Clock skew (ns) | 0 (by definition) | {q.fmt(skew, '{:.3f}')} |",
         f"| Insertion delay / latency (ns) | 0 | {q.fmt(lat, '{:.3f}')} |",
         f"| Clock buffers added | 0 | {q.fmt(clk_bufs_total, '{:.0f}')} |",
         f"| Hold worst slack — before repair (ns) | n/a (no skew) | {q.fmt(pre_hold, '{:+.3f}')} |",
         f"| Hold worst slack — after repair (ns) | n/a | {q.fmt(post_hold, '{:+.3f}')} |",
         "",
         "**Why hold breaks at CTS and not before:** with an ideal clock the launch"
         " and capture edges are simultaneous, so short paths have huge hold margin."
         " CTS gives the clock real insertion delay and **skew** between launch and"
         " capture sinks; that skew eats directly into the hold budget"
         " (`slack_hold = t_clk2q + t_comb(min) - t_hold - skew`), creating the"
         f" violations above (worst {q.fmt(pre_hold,'{:+.3f}')} ns). `repair_timing -hold`"
         " then inserts delay cells until the post-repair worst hold is"
         f" {q.fmt(post_hold,'{:+.3f}')} ns.", "",
         "## Clock-tree topology"]

    for d in topo:
        L += ["", f"### Clock net `{d['net']}`  ({d['sinks']} sinks)",
              f"- buffers: **{d['buffers']}** (leaf {d['leaf']})",
              f"- buffers in clock path: {d['minp']}–{d['maxp']}",
              f"- tree levels: {d['level']}"]

    # mermaid sketch of the focused domain
    foc = next((d for d in topo if d["net"] == a.clock_net), topo[0] if topo else None)
    if foc:
        L += ["", f"### Topology sketch — `{foc['net']}`", "", "```mermaid",
              "flowchart TD",
              f'  CLK["clk_i (root)"] --> R["root + internal buffers<br/>{foc["buffers"]} total, {foc["level"]} levels"]',
              f'  R --> LEAF["{foc["leaf"]} leaf buffers"]',
              f'  LEAF --> SINKS["{foc["sinks"]} sink flip-flops<br/>{foc["minp"]}–{foc["maxp"]} buffers deep"]',
              "```", ""]

    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    open(a.out, "w").write("\n".join(L))
    print(f"wrote {a.out}")
    print(f"  pre-repair hold WS:  {pre_hold}")
    print(f"  post-repair hold WS: {post_hold}")
    print(f"  skew={skew} insertion={lat} clk_bufs_total={clk_bufs_total}")
    for d in topo:
        print(f"  {d['net']}: sinks={d['sinks']} bufs={d['buffers']} levels={d['level']}")


if __name__ == "__main__":
    sys.exit(main())
